
CONNECTION_KIND_HTTP_LOCAL = "HTTP_LOCAL"
CONNECTION_KIND_HTTP_REMOTE_BASIC = "HTTP_REMOTE_BASIC"

CONNECTION_KINDS = {
    CONNECTION_KIND_HTTP_LOCAL,
    CONNECTION_KIND_HTTP_REMOTE_BASIC,
}

HTTP_METHOD_POST = "POST"


AUTH_TYPE_NONE = "none"
AUTH_TYPE_BEARER = "bearer"
AUTH_TYPE_BASIC = "basic"

AUTH_TYPES = {
    AUTH_TYPE_NONE,
    AUTH_TYPE_BEARER,
    AUTH_TYPE_BASIC,
}

DEFAULT_HTTP_METHOD = HTTP_METHOD_POST
DEFAULT_TIMEOUT = 20.0
