
CONNECTION_KIND_MCP = "MCP"
CONNECTION_KIND_HTTP_LOCAL = "HTTP_LOCAL"
CONNECTION_KIND_HTTP_REMOTE_BASIC = "HTTP_REMOTE_BASIC"

CONNECTION_KINDS = {
    CONNECTION_KIND_MCP,
    CONNECTION_KIND_HTTP_LOCAL,
    CONNECTION_KIND_HTTP_REMOTE_BASIC,
}

HTTP_METHOD_POST = "POST"


AUTH_TYPE_NONE = "none"
AUTH_TYPE_BEARER = "bearer"
AUTH_TYPE_BASIC = "basic"

AUTH_TYPES = {
    AUTH_TYPE_NONE,
    AUTH_TYPE_BEARER,
    AUTH_TYPE_BASIC,
}

TRANSPORT_HTTP = "http"
TRANSPORT_SSE = "sse"
TRANSPORT_STDIO = "stdio"

TRANSPORTS = {
    TRANSPORT_HTTP,
    TRANSPORT_SSE,
    TRANSPORT_STDIO,
}
DEFAULT_TRANSPORT = TRANSPORT_HTTP
DEFAULT_HTTP_METHOD = HTTP_METHOD_POST
DEFAULT_TIMEOUT = 20.0